parameters:
    domain.mq.exchange_options: {name: 'message_bus.exchange1', type: direct}
    domain.mq.graceful_max_execution: {timeout: 1800, exit_code: 0}

old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(string:RABBITMQ_URL)%'
            lazy: true
            connection_timeout: 10
            read_write_timeout: 10
            keepalive: false # requires php-amqplib v2.4.1+ and PHP5.4+
            heartbeat: 180 # requires php-amqplib v2.4.1+
            use_socket: false

    producers:
        message_bus_exchange:
            connection: default
            exchange_options: '%domain.mq.exchange_options%'
            class: App\RabbitMq\Producer

    consumers:
        message_bus:
            exchange_options: '%domain.mq.exchange_options%'
            graceful_max_execution: '%domain.mq.graceful_max_execution%'
            connection: default
            queue_options: { name: 'messages', routing_keys: [ 'messages' ] }
            callback: App\RabbitMq\Consumer
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}


when@prod:
    old_sound_rabbit_mq:
        connections:
            default:
                ssl_context:
                    verify_peer: false
                    verify_peer_name: false
